#!/bin/sh

export LOCATION=eastus
export LOCATION_2=westus

export ENVIRONMENT=dev
export PROJECT=petstore

export RESOURCE_GROUP="rg-${PROJECT}"
export CONTAINER_REGISTRY="cr${PROJECT}${ENVIRONMENT}"
export SERVICE_PLAN_SKU=B1
export SERVICE_PLAN_WEB_APP_SKU=S1

export WEP_APP_NAME=webapp
export WEB_APP_IMAGE="petstore-${WEP_APP_NAME}"
export WEP_APP_SUBDOMAIN="app-${WEP_APP_NAME}-${PROJECT}-${ENVIRONMENT}-${LOCATION}-001"
export WEP_APP_SUBDOMAIN_2="app-${WEP_APP_NAME}-${PROJECT}-${ENVIRONMENT}-${LOCATION_2}-001"
export WEB_APP_SERVICE_PLAN="sp-${WEP_APP_SUBDOMAIN}"
export WEB_APP_SERVICE_PLAN_2="sp-${WEP_APP_SUBDOMAIN_2}"

export PET_SERVICE_NAME=petservice
export PET_SERVICE_IMAGE="petstore-${PET_SERVICE_NAME}"
export PET_SERVICE_SUBDOMAIN="app-${PET_SERVICE_NAME}-${PROJECT}-${ENVIRONMENT}-001"
export PET_SERVICE_SERVICE_PLAN="sp-${PET_SERVICE_SUBDOMAIN}"

export PRODUCT_SERVICE_NAME=productservice
export PRODUCT_SERVICE_IMAGE="petstore-${PRODUCT_SERVICE_NAME}"
export PRODUCT_SERVICE_SUBDOMAIN="app-${PRODUCT_SERVICE_NAME}-${PROJECT}-${ENVIRONMENT}-001"
export PRODUCT_SERVICE_SERVICE_PLAN="sp-${PRODUCT_SERVICE_SUBDOMAIN}"

export ORDER_SERVICE_NAME=orderservice
export ORDER_SERVICE_IMAGE="petstore-${ORDER_SERVICE_NAME}"
export ORDER_SERVICE_SUBDOMAIN="app-${ORDER_SERVICE_NAME}-${PROJECT}-${ENVIRONMENT}-001"
export ORDER_SERVICE_SERVICE_PLAN="sp-${ORDER_SERVICE_SUBDOMAIN}"

export TRAFFIC_MANAGER_PROFILE=tm-${PROJECT}-${WEP_APP_NAME}

export WEB_APP_AUTOSCALE=autoscale-${WEP_APP_SUBDOMAIN}
export WEB_APP_AUTOSCALE_2=autoscale-${WEP_APP_SUBDOMAIN_2}

export DEPLOYMENT_SLOT=staging

export DB_SERVER_NAME=petstore-db-server
export DB_NAME=postgres
export DB_ADMIN_USER=sparvov
export DB_ADMIN_PASSWORD=Qwerty@12345

export DATASOURCE_DB_HOST=${DB_SERVER_NAME}.postgres.database.azure.com
export DATASOURCE_DB_PORT=5432
export DATASOURCE_DB_NAME=${DB_NAME}
export DATASOURCE_DB_URL=jdbc:postgresql://${DATASOURCE_DB_HOST}:${DATASOURCE_DB_PORT}/${DATASOURCE_DB_NAME}?sslmode=require
export DATASOURCE_DB_USERNAME=${DB_ADMIN_USER}@${DB_SERVER_NAME}
export DATASOURCE_DB_PASSWORD=${DB_ADMIN_PASSWORD}

export MY_IP_ADDRESS=$(curl http://whatismyip.akamai.com/)

export KEY_VAULT_NAME=petstore-keyvault-123
export KEY_VAULT_SECRET_NAME_DB_URL=keyVaultSecretNameDbUrl
export KEY_VAULT_SECRET_NAME_DB_USERNAME=keyVaultSecretNameDbUserName
export KEY_VAULT_SECRET_NAME_DB_PASSWORD=keyVaultSecretNameDbPassword
export KEY_VAULT_SECRET_NAME_COSMOS_URI=keyVaultSecretNameCosmosUri
export KEY_VAULT_SECRET_NAME_COSMOS_PRIMARY_KEY=keyVaultSecretNameCosmosPrimaryKey
export KEY_VAULT_SECRET_NAME_COSMOS_SECONDARY_KEY=keyVaultSecretNameCosmosSecondaryKey
export KEY_VAULT_SECRET_NAME_COSMOS_DB_NAME=keyVaultSecretNameCosmosDbName

export COSMOS_DB_ACCOUNT_NAME=petstore-account
export COSMOS_DB_NAME=Orders
export COSMOS_URI=https://${COSMOS_DB_ACCOUNT_NAME}.documents.azure.com:443/
