#!/bin/sh

export LOCATION=eastus
export LOCATION_2=westus

export ENVIRONMENT=dev
export PROJECT=petstore

export RESOURCE_GROUP="rg-${PROJECT}"
export CONTAINER_REGISTRY="cr${PROJECT}${ENVIRONMENT}"
export SERVICE_PLAN_SKU=B1
export SERVICE_PLAN_WEB_APP_SKU=S1

export WEP_APP_NAME=webapp
export WEB_APP_IMAGE="petstore-${WEP_APP_NAME}"
export WEP_APP_SUBDOMAIN="app-${WEP_APP_NAME}-${PROJECT}-${ENVIRONMENT}-${LOCATION}-001"
export WEP_APP_SUBDOMAIN_2="app-${WEP_APP_NAME}-${PROJECT}-${ENVIRONMENT}-${LOCATION_2}-001"
export WEB_APP_SERVICE_PLAN="sp-${WEP_APP_SUBDOMAIN}"
export WEB_APP_SERVICE_PLAN_2="sp-${WEP_APP_SUBDOMAIN_2}"

export PET_SERVICE_NAME=petservice
export PET_SERVICE_IMAGE="petstore-${PET_SERVICE_NAME}"
export PET_SERVICE_SUBDOMAIN="app-${PET_SERVICE_NAME}-${PROJECT}-${ENVIRONMENT}-001"
export PET_SERVICE_SERVICE_PLAN="sp-${PET_SERVICE_SUBDOMAIN}"

export PRODUCT_SERVICE_NAME=productservice
export PRODUCT_SERVICE_IMAGE="petstore-${PRODUCT_SERVICE_NAME}"
export PRODUCT_SERVICE_SUBDOMAIN="app-${PRODUCT_SERVICE_NAME}-${PROJECT}-${ENVIRONMENT}-001"
export PRODUCT_SERVICE_SERVICE_PLAN="sp-${PRODUCT_SERVICE_SUBDOMAIN}"

export ORDER_SERVICE_NAME=orderservice
export ORDER_SERVICE_IMAGE="petstore-${ORDER_SERVICE_NAME}"
export ORDER_SERVICE_SUBDOMAIN="app-${ORDER_SERVICE_NAME}-${PROJECT}-${ENVIRONMENT}-001"
export ORDER_SERVICE_SERVICE_PLAN="sp-${ORDER_SERVICE_SUBDOMAIN}"

export TRAFFIC_MANAGER_PROFILE=tm-${PROJECT}-${WEP_APP_NAME}

export AUTOSCALE_NAME=autoscale-${WEP_APP_SUBDOMAIN}
